{% set version = '2.0.5' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ashr
  version: {{ version|replace("-", "_") }}

source:
  fn: ashr_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/ashr_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/ashr/ashr_{{ version }}.tar.gz


  sha256: bf3864a868f3224a81a38233d9a25990b63316446dd2f86397dc2a76630a992e
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, roxygen2, covr
requirements:
  build:
    - r-base
    - r-rcpp >=0.10.5
    - r-squarem
    - r-assertthat
    - r-doparallel
    - r-etrunct
    - r-foreach
    - r-pscl
    - r-truncnorm
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - r-rcpp >=0.10.5
    - r-squarem
    - r-assertthat
    - r-doparallel
    - r-etrunct
    - r-foreach
    - r-pscl
    - r-truncnorm
    - libgcc  # [not win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('ashr')"  # [not win]
    - "\"%R%\" -e \"library('ashr')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://github.com/stephens999/ashr
  license: GPL (>= 3)
  summary: 'The R package ''ashr'' implements an Empirical Bayes approach for large-scale hypothesis
    testing and false discovery rate (FDR) estimation based on the methods proposed
    in M. Stephens, 2016, "False discovery rates: a new deal", <DOI:10.1093/biostatistics/kxw041>.
    These methods can be applied whenever two sets of summary statistics---estimated
    effects and standard errors---are available, just as ''qvalue'' can be applied to
    previously computed p-values. Two main interfaces are provided: ash(), which is
    more user-friendly; and ash.workhorse(), which has more options and is geared toward
    advanced users.'

  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: ashr
# Maintainer: Peter Carbonetto <pcarbo@uchicago.edu>
# Author: Matthew Stephens, Chaoxing Dai, Mengyin Lu, David Gerard, Nan Xiao, Peter Carbonetto
# Version: 2.0.5
# Date: 2016-12-15
# Title: Methods for Adaptive Shrinkage, using Empirical Bayes
# Description: The R package 'ashr' implements an Empirical Bayes approach for large-scale hypothesis testing and false discovery rate (FDR) estimation based on the methods proposed in M. Stephens, 2016, "False discovery rates: a new deal", <DOI:10.1093/biostatistics/kxw041>. These methods can be applied whenever two sets of summary statistics---estimated effects and standard errors---are available, just as 'qvalue' can be applied to previously computed p-values. Two main interfaces are provided: ash(), which is more user-friendly; and ash.workhorse(), which has more options and is geared toward advanced users.
# Depends: R (>= 3.1.0)
# Imports: assertthat, truncnorm, SQUAREM, doParallel, pscl, Rcpp (>= 0.10.5), foreach, etrunct
# LinkingTo: Rcpp
# Suggests: testthat, roxygen2, covr
# Enhances: REBayes, Rmosek
# License: GPL (>= 3)
# NeedsCompilation: yes
# URL: http://github.com/stephens999/ashr
# RoxygenNote: 5.0.1
# Packaged: 2016-12-27 13:56:26 UTC; hornik
# Repository: CRAN
# Date/Publication: 2016-12-27 15:28:19

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
