{% set version = '0.10.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-workflowr
  version: {{ version|replace("-", "_") }}

source:
  git_url: https://github.com/jdblischak/workflowr
  git_tag: v0.10.1

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-r.utils
    - r-callr
    - r-getpass
    - r-git2r
    - r-rmarkdown >=0.9.6
    - r-rprojroot
    - r-rstudioapi
    - r-stringr >=1.1.0
    - r-whisker
    - r-yaml

  run:
    - r-base
    - r-r.utils
    - r-callr
    - r-getpass
    - r-git2r
    - r-rmarkdown >=0.9.6
    - r-rprojroot
    - r-rstudioapi
    - r-stringr >=1.1.0
    - r-whisker
    - r-yaml

test:
  commands:
    - $R -e "library('workflowr')"  # [not win]
    - "\"%R%\" -e \"library('workflowr')\""  # [win]

about:
  home: https://github.com/jdblischak/workflowr
  license: MIT
  summary: workflowr provides helper functions to get started using R Markdown to create a research
    website.
  license_family: MIT
