{% set version = '2016.8-2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-squarem
  version: {{ version|replace("-", "_") }}

source:
  fn: SQUAREM_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/SQUAREM_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/SQUAREM/SQUAREM_{{ version }}.tar.gz


  sha256: 13d0bd9161620c3c3f794116d224b83b66ccb1479a7dc076c918ec2235dadcc7
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: setRNG
requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('SQUAREM')"  # [not win]
    - "\"%R%\" -e \"library('SQUAREM')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://www.jhsph.edu/agingandhealth/People/Faculty_personal_pages/Varadhan.html
  license: GPL (>= 2)
  summary: Algorithms for accelerating the convergence of slow, monotone sequences from smooth,
    contraction mapping such as the EM algorithm. It can be used to accelerate any smooth,
    linearly convergent acceleration scheme.  A tutorial style introduction to this
    package is available in a vignette on the CRAN download page or, when the package
    is loaded in an R session, with vignette("SQUAREM").
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: SQUAREM
# Version: 2016.8-2
# Date: 2016-08-17
# Title: Squared Extrapolation Methods for Accelerating EM-Like Monotone Algorithms
# Description: Algorithms for accelerating the convergence of slow, monotone sequences from smooth, contraction mapping such as the EM algorithm. It can be used to accelerate any smooth, linearly convergent acceleration scheme.  A tutorial style introduction to this package is available in a vignette on the CRAN download page or, when the package is loaded in an R session, with vignette("SQUAREM").
# Depends: R (>= 3.0)
# Suggests: setRNG
# LazyLoad: yes
# License: GPL (>= 2)
# Author: Ravi Varadhan
# Maintainer: Ravi Varadhan <ravi.varadhan@jhu.edu>
# URL: http://www.jhsph.edu/agingandhealth/People/Faculty_personal_pages/Varadhan.html
# Repository: CRAN
# NeedsCompilation: no
# Packaged: 2016-08-18 16:13:21 UTC; rvaradh1
# Date/Publication: 2016-08-18 23:27:39

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
