package:
  name: bioconductor-confess
  version: 1.2.2
source:
  fn: CONFESS_1.2.2.tar.gz
  url:
    - http://bioconductor.org/packages/3.4/bioc/src/contrib/CONFESS_1.2.2.tar.gz
    - https://depot.galaxyproject.org/software/CONFESS/CONFESS_1.2.2_src_all.tar.gz
  md5: 86f89638e3d74e3f3badc51bf680c426
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-ebimage
    - bioconductor-flowclust
    - bioconductor-flowcore
    - bioconductor-flowmeans
    - bioconductor-flowmerge
    - bioconductor-flowpeaks
    - bioconductor-limma
    - bioconductor-samspectral
    - r-base
    - r-changepoint
    - r-cluster
    - r-contrast
    - r-ecp
    - r-flexmix
    - r-foreach
    - r-ggplot2
    - r-mass
    - r-moments
    - r-outliers
    - r-plotrix
    - r-raster
    - r-readbitmap
    - r-reshape2
    - r-waveslim
    - r-wavethresh
    - r-zoo
  run:
    - bioconductor-ebimage
    - bioconductor-flowclust
    - bioconductor-flowcore
    - bioconductor-flowmeans
    - bioconductor-flowmerge
    - bioconductor-flowpeaks
    - bioconductor-limma
    - bioconductor-samspectral
    - r-base
    - r-changepoint
    - r-cluster
    - r-contrast
    - r-ecp
    - r-flexmix
    - r-foreach
    - r-ggplot2
    - r-mass
    - r-moments
    - r-outliers
    - r-plotrix
    - r-raster
    - r-readbitmap
    - r-reshape2
    - r-waveslim
    - r-wavethresh
    - r-zoo
test:
  commands:
    - '$R -e "library(''CONFESS'')"'
about:
  home: http://bioconductor.org/packages/3.4/bioc/html/CONFESS.html
  license: GPL-2
  summary: 'Single Cell Fluidigm Spot Detector.'
