{% set version = '0.1.2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-cellcycler
  version: {{ version|replace("-", "_") }}

source:
  git_url: https://github.com/jhsiao999/cellcycleR
  git_tag: 0.1.2

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-mass
    - r-binhf
    - r-wavethresh
    - r-zoo

  run:
    - r-base
    - r-mass
    - r-binhf
    - r-wavethresh
    - r-zoo

test:
  commands:
    - $R -e "library('cellcycleR')"  # [not win]
    - "\"%R%\" -e \"library('cellcycleR')\""  # [win]

about:
  home: https://github.com/jhsiao999/cellcycleR
  license: GPL (>= 2)
  summary: From gene expression data, filters out the sinusoidal genes and outputs relative times
    of the cells on the cell cycle.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]
