{% set version = '0.2-9' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mashr
  version: {{ version|replace("-", "_") }}

source:
  git_url: https://github.com/stephenslab/mashr
  git_tag: v0.2-9

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake          # [not win]
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-ashr (>= 2.1_19)
    - r-assertthat
    - r-base
    - r-mvtnorm
    - r-plyr
    - r-rcpp (>= 0.12.11)
    - r-rcpparmadillo
    - r-rmeta

  run:
    - r-ashr (>= 2.1_19)
    - r-assertthat
    - r-base
    - r-mvtnorm
    - r-plyr
    - r-rcpp (>= 0.12.11)
    - r-rcpparmadillo
    - r-rmeta
    - {{native}}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('mashr')"           # [not win]
    - "\"%R%\" -e \"library('mashr')\""  # [win]

about:
  home: http://github.com/stephenslab/mashr
  license: BSD 3-clause
  summary: Empirical Bayes shrinkage of multivariate effects.
  license_family: BSD
  license_file: LICENSE

