package:
  name: bioconductor-samspectral
  version: 1.28.0
source:
  fn: SamSPECTRAL_1.28.0.tar.gz
  url:
    - http://bioconductor.org/packages/3.4/bioc/src/contrib/SamSPECTRAL_1.28.0.tar.gz
    - https://bioarchive.galaxyproject.org/SamSPECTRAL_1.28.0.tar.gz
    - https://depot.galaxyproject.org/software/SamSPECTRAL/SamSPECTRAL_1.28.0_src_all.tar.gz
  md5: 615a3b87f79fba9b83c9a305bcc21d3f
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - r-base
  run:
    - r-base
test:
  commands:
    - '$R -e "library(''SamSPECTRAL'')"'
about:
  home: http://bioconductor.org/packages/3.4/bioc/html/SamSPECTRAL.html
  license: 'GPL (>= 2)'
  summary: 'Samples large data such that spectral clustering is possible while preserving
    density information in edge weights. More specifically, given a matrix of coordinates
    as input, SamSPECTRAL first builds the communities to sample the data points.
    Then, it builds a graph and after weighting the edges by conductance computation,
    the graph is passed to a classic spectral clustering algorithm to find the spectral
    clusters. The last stage of SamSPECTRAL is to combine the spectral clusters. The
    resulting "connected components" estimate biological cell populations in the data
    sample. For instructions on manual installation, refer to the PDF file provided
    in the following documentation.'
