{% set version = '1.0.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-coga
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/coga_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/coga/coga_{{ version }}.tar.gz
  sha256: 267caabcd5c83c3b0757871b9c4697eae6c28d93f58742262d05e9d06493a357

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake          # [not win]
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-rcpp
    - r-rcppgsl

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp
    - r-rcppgsl

test:
  commands:
    - $R -e "library('coga')"           # [not win]
    - "\"%R%\" -e \"library('coga')\""  # [win]

about:
  home: https://github.com/ChaoranHu/coga
  license: GPL (>= 3.0)
  summary: Evaluation for density and distribution function of convolution of gamma distributions
    in R. Two related exact methods and one approximate method are implemented with
    efficient algorithm and C++ code. A quick guide for choosing correct method and
    usage of this package is given in package vignette.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

# The original CRAN metadata for this package was:

# Package: coga
# Title: Convolution of Gamma Distributions
# Version: 1.0.0
# Date: 2018-05-08
# Authors@R: c( person("Chaoran", "Hu", email = "chaoran.hu@uconn.edu", role = c("aut", "cre")), person("Vladimir", "Pozdnyakov", email = "vladimir.pozdnyakov@uconn.edu", role = "ths"), person("Jun", "Yan", email = "jun.yan@uconn.edu", role = "ths"))
# Description: Evaluation for density and distribution function of convolution of gamma distributions in R. Two related exact methods and one approximate method are implemented with efficient algorithm and C++ code. A quick guide for choosing correct method and usage of this package is given in package vignette.
# Depends: R (>= 3.3.0)
# License: GPL (>= 3.0)
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.0.1
# Suggests: testthat, R.rsp
# Imports: stats, Rcpp
# LinkingTo: Rcpp, RcppGSL
# VignetteBuilder: R.rsp
# BugReports: https://github.com/ChaoranHu/coga/issues
# URL: https://github.com/ChaoranHu/coga
# NeedsCompilation: yes
# SystemRequirements: GNU GSL
# Packaged: 2018-05-08 19:38:27 UTC; ChaoranHu
# Author: Chaoran Hu [aut, cre], Vladimir Pozdnyakov [ths], Jun Yan [ths]
# Maintainer: Chaoran Hu <chaoran.hu@uconn.edu>
# Repository: CRAN
# Date/Publication: 2018-05-08 19:51:46 UTC
