{% set version = '0.2.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-seqgendiff
  version: {{ version|replace("-", "_") }}

source:

  git_url: https://github.com/dcgerard/seqgendiff
  git_tag: v0.2.0

build:
  merge_build_host: True  # [win]
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}filesystem        # [win]
    - {{posix}}git
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-assertthat
    - r-irlba

  run:
    - r-base
    - r-assertthat
    - r-irlba

test:
  commands:
    - $R -e "library('seqgendiff')"           # [not win]
    - "\"%R%\" -e \"library('seqgendiff')\""  # [win]

about:
  home: https://github.com/dcgerard/seqgendiff
  license: GPL-3
  summary: Modifies/generates RNA-seq data for use in simulations.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

# Package: seqgendiff
# Type: Package
# Title: Sequence Generation for Differential Expression Analysis
# Version: 0.2.0
# Authors@R: person("David", "Gerard", email = "dgerard@american.edu", role = c("aut", "cre"))
# Description: Modifies/generates RNA-seq data for use in simulations.
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# URL: https://github.com/dcgerard/seqgendiff
# BugReports: http://github.com/dcgerard/seqgendiff/issues
# RoxygenNote: 6.1.1
# Suggests: covr, testthat
# Imports: assertthat, irlba
