{% set version = '0.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-etrunct
  version: {{ version|replace("-", "_") }}

source:
  fn: etrunct_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/etrunct_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/etrunct/etrunct_{{ version }}.tar.gz


  sha256: 19b36c739e382be2f19bdbe4107337935d52a1ab8eb301326612318afdfbca2b
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat
requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('etrunct')"  # [not win]
    - "\"%R%\" -e \"library('etrunct')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=etrunct
  license: MIT + file LICENSE
  summary: Computes moments of univariate truncated t distribution. There is only one exported
    function, e_trunct(), which should be seen for details.
  license_family: MIT

# The original CRAN metadata for this package was:

# Package: etrunct
# Type: Package
# Title: Computes Moments of Univariate Truncated t Distribution
# Version: 0.1
# Author: Matthew Stephens
# Maintainer: Matthew Stephens <mstephens@uchicago.edu>
# Description: Computes moments of univariate truncated t distribution. There is only one exported function, e_trunct(), which should be seen for details.
# License: MIT + file LICENSE
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 5.0.1
# Suggests: testthat
# NeedsCompilation: no
# Packaged: 2016-07-03 15:43:09 UTC; stephens
# Repository: CRAN
# Date/Publication: 2016-07-04 09:12:55

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
