{% set name = "Wand" %}
{% set version = "0.5.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 52763dbf65d00cf98d7bc910b49329eea15896249c5555d47e169f2b6efbe166

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python
    - imagemagick

test:
  imports:
    - wand
    - wand.cdefs
  files:
    - test.py
    - test.jpg
  commands:
    - python test.py

about:
  home: http://wand-py.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Ctypes-based simple MagickWand API binding for Python"
  doc_url: http://docs.wand-py.org/
  dev_url: https://github.com/emcconville/wand

extra:
  recipe-maintainers:
    - BoPeng
    - gaow
    - jdblischak
