{% set version = '1.3-15' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rodbc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RODBC_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RODBC/RODBC_{{ version }}.tar.gz
  sha256: c43e5a2f0aa2f46607e664bfc0bb3caa230bbb779f4ff084e01727642da136e1

build:
  merge_build_host: True  # [win]
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake          # [not win]
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - unixodbc                   # [unix]

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - unixodbc                   # [unix]

test:
  commands:
    - $R -e "library('RODBC')"           # [not win]
    - "\"%R%\" -e \"library('RODBC')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=RODBC
  license: GPL-2 | GPL-3
  summary: An ODBC database interface.
  license_family: GPL3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: RODBC
# Version: 1.3-15
# Revision: $Rev: 3476 $
# Date: 2017-04-13
# Authors@R: c(person("Brian", "Ripley", role = c("aut", "cre"), email = "ripley@stats.ox.ac.uk"), person("Michael", "Lapsley", role = "aut",  comment = "1999 to Oct 2002"))
# Title: ODBC Database Access
# Description: An ODBC database interface.
# SystemRequirements: An ODBC3 driver manager and drivers.
# Depends: R (>= 3.0.0)
# Imports: stats
# LazyLoad: yes
# Biarch: yes
# License: GPL-2 | GPL-3
# NeedsCompilation: yes
# Packaged: 2017-05-05 10:50:09 UTC; ripley
# Author: Brian Ripley [aut, cre], Michael Lapsley [aut] (1999 to Oct 2002)
# Maintainer: Brian Ripley <ripley@stats.ox.ac.uk>
# Repository: CRAN
# Date/Publication: 2017-05-05 12:56:27
